# Generated by Django 5.2.9 on 2025-12-23 16:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الفئة')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='الأيقونة')),
                ('order', models.IntegerField(default=0, verbose_name='الترتيب')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'فئة تقارير',
                'verbose_name_plural': 'فئات التقارير',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان التقرير')),
                ('description', models.TextField(verbose_name='وصف التقرير')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('in_progress', 'قيد المعالجة'), ('resolved', 'تم الحل'), ('rejected', 'مرفوض'), ('closed', 'مغلق')], default='pending', max_length=20, verbose_name='الحالة')),
                ('priority', models.CharField(choices=[('low', 'منخفض'), ('medium', 'متوسط'), ('high', 'مرتفع'), ('critical', 'حرج')], default='medium', max_length=20, verbose_name='الأولوية')),
                ('severity', models.IntegerField(choices=[(1, 'منخفض'), (2, 'متوسط'), (3, 'مرتفع')], default=1, verbose_name='الخطورة')),
                ('evidence_files', models.FileField(blank=True, null=True, upload_to='reports/evidence/', verbose_name='ملفات الإثبات')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='الموقع')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإبلاغ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحل')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الاستحقاق')),
                ('view_count', models.IntegerField(default=0, verbose_name='عدد المشاهدات')),
                ('is_public', models.BooleanField(default=False, verbose_name='عام')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_reports', to=settings.AUTH_USER_MODEL, verbose_name='المسؤول عن المعالجة')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_reports', to=settings.AUTH_USER_MODEL, verbose_name='المبلغ')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='reports.reportcategory', verbose_name='الفئة')),
            ],
            options={
                'verbose_name': 'تقرير',
                'verbose_name_plural': 'التقارير',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='محتوى التعليق')),
                ('is_internal', models.BooleanField(default=False, verbose_name='تعليق داخلي')),
                ('attachments', models.FileField(blank=True, null=True, upload_to='reports/comments/', verbose_name='المرفقات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التعليق')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_comments', to=settings.AUTH_USER_MODEL, verbose_name='المعلق')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='reports.report', verbose_name='التقرير')),
            ],
            options={
                'verbose_name': 'تعليق تقرير',
                'verbose_name_plural': 'تعليقات التقارير',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(max_length=20, verbose_name='الحالة السابقة')),
                ('new_status', models.CharField(max_length=20, verbose_name='الحالة الجديدة')),
                ('reason', models.TextField(blank=True, verbose_name='سبب التغيير')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التغيير')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='تم التغيير بواسطة')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='reports.report', verbose_name='التقرير')),
            ],
            options={
                'verbose_name': 'تاريخ حالة التقرير',
                'verbose_name_plural': 'تاريخ حالات التقارير',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم النوع')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('severity_level', models.IntegerField(choices=[(1, 'منخفض'), (2, 'متوسط'), (3, 'مرتفع')], default=1, verbose_name='مستوى الخطورة')),
                ('sla_days', models.IntegerField(default=3, verbose_name='مدة الاستجابة (أيام)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types', to='reports.reportcategory', verbose_name='الفئة')),
            ],
            options={
                'verbose_name': 'نوع تقرير',
                'verbose_name_plural': 'أنواع التقارير',
                'ordering': ['category', 'severity_level'],
            },
        ),
        migrations.AddField(
            model_name='report',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='reports.reporttype', verbose_name='نوع التقرير'),
        ),
    ]
