# Generated by Django 5.2.9 on 2025-12-22 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thread',
            options={'ordering': ['-created_at'], 'verbose_name': 'موضوع', 'verbose_name_plural': 'المواضيع'},
        ),
        migrations.RemoveField(
            model_name='thread',
            name='is_locked',
        ),
        migrations.RemoveField(
            model_name='thread',
            name='is_pinned',
        ),
        migrations.AddField(
            model_name='forumcategory',
            name='icon',
            field=models.CharField(blank=True, max_length=50, verbose_name='الأيقونة'),
        ),
        migrations.AddField(
            model_name='reply',
            name='is_solution',
            field=models.BooleanField(default=False, verbose_name='هل هو حل؟'),
        ),
        migrations.AddField(
            model_name='reply',
            name='likes',
            field=models.IntegerField(default=0, verbose_name='الإعجابات'),
        ),
        migrations.AddField(
            model_name='thread',
            name='likes',
            field=models.IntegerField(default=0, verbose_name='الإعجابات'),
        ),
        migrations.AddField(
            model_name='thread',
            name='status',
            field=models.CharField(choices=[('open', 'مفتوح'), ('closed', 'مغلق'), ('pinned', 'مثبت')], default='open', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخر تحديث'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخر تحديث'),
        ),
        migrations.CreateModel(
            name='ForumVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_type', models.CharField(choices=[('like', 'إعجاب'), ('dislike', 'عدم إعجاب')], max_length=10, verbose_name='نوع التصويت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التصويت')),
                ('reply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='forum.reply', verbose_name='الرد')),
                ('thread', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='forum.thread', verbose_name='الموضوع')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'تصويت',
                'verbose_name_plural': 'التصويتات',
                'unique_together': {('user', 'reply'), ('user', 'thread')},
            },
        ),
    ]
