# Generated by Django 5.2.9 on 2025-12-22 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorialCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الفئة')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='الأيقونة')),
                ('color', models.CharField(default='#3498db', max_length=20, verbose_name='اللون')),
                ('order', models.IntegerField(default=0, verbose_name='الترتيب')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'فئة دروس',
                'verbose_name_plural': 'فئات الدروس',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='الرابط')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('content', models.TextField(verbose_name='المحتوى')),
                ('level', models.CharField(choices=[('beginner', 'مبتدئ'), ('intermediate', 'متوسط'), ('advanced', 'متقدم')], default='beginner', max_length=20, verbose_name='المستوى')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('published', 'منشور'), ('archived', 'مؤرشف')], default='draft', max_length=20, verbose_name='الحالة')),
                ('estimated_time', models.IntegerField(default=30, verbose_name='الوقت المقدر (دقيقة)')),
                ('views', models.IntegerField(default=0, verbose_name='المشاهدات')),
                ('likes', models.IntegerField(default=0, verbose_name='الإعجابات')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='tutorials/thumbnails/', verbose_name='الصورة المصغرة')),
                ('video_url', models.URLField(blank=True, verbose_name='رابط الفيديو')),
                ('attachments', models.FileField(blank=True, null=True, upload_to='tutorials/attachments/', verbose_name='المرفقات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ النشر')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutorials', to=settings.AUTH_USER_MODEL, verbose_name='المؤلف')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutorials', to='tutorials.tutorialcategory', verbose_name='الفئة')),
            ],
            options={
                'verbose_name': 'درس',
                'verbose_name_plural': 'الدروس',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TutorialSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان القسم')),
                ('content', models.TextField(verbose_name='محتوى القسم')),
                ('order', models.IntegerField(default=0, verbose_name='الترتيب')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('tutorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='tutorials.tutorial', verbose_name='الدرس')),
            ],
            options={
                'verbose_name': 'قسم درس',
                'verbose_name_plural': 'أقسام الدروس',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='UserTutorialProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_sections', models.JSONField(default=list, verbose_name='الأقسام المكتملة')),
                ('is_completed', models.BooleanField(default=False, verbose_name='مكتمل')),
                ('completion_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإكمال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ البدء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('tutorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='tutorials.tutorial', verbose_name='الدرس')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutorial_progress', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'تقدم المستخدم',
                'verbose_name_plural': 'تقدم المستخدمين',
                'unique_together': {('user', 'tutorial')},
            },
        ),
    ]
